### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by nihilistzsche** [dehesselle/vmmctl#3]
Hello,

  You do not have a LICENSE file in this repo, under what conditions is this shared?

Im making a PKGBUILD for arch linux and need license information.

**Comment by dehesselle** [comment]
Hi!
Thank you for your interest. The missing license is an oversight, I've just added the MIT license. (Not being an expert at this stuff, my intention is that scripts and configurations are only useful if you are allowed to do everything with it, the only ask being a back reference to the source.) I hope that is suitable for you.

May I ask where/how you are going to use this? Because that might be incentive enough for me to apply more polish, e.g. bringing the documentation up to speed (most notable discrepancy: the readme still thinks the service's name is vm, but it's kvm) or put in further development efforts.

**Comment by nihilistzsche** [comment]
Im creating a PKGBUILD for arch for myself, I will put it up on github soon for you to look at.  I have to patch some things around but otherwise it works great.  I figured it was oversight and thank you for the answering :)

I've actually been using this for a while now, and saw how you had pushed some updates to git that I had missed, so putting this in a PKGBUILD and letting my AUR helper handle it will help me keep up with git commits you make.

**Comment by dehesselle** [comment]
Cool - it's always nice to hear when somebody can actually make use of something 😃
Although my focus right now is on another project of mine, virtctl is not dead. So you won't be creating the PKGBUILD for nothing, there will be further updates.

**Comment by nihilistzsche** [comment]
https://aur.archlinux.org/packages/virtctl-git/

The patches just change the binary location from /usr/local/sbin to /usr/bin (Arch does not have sbin), and the configuration file from /usr/local/etc to /etc/virtctl.

**Comment by nihilistzsche** [comment]
As the license has been added to the repo this issue can now be closed, feel free to rearch out to me if you have any concerns with the package.
